#!bash (. my2)
# The following is created by humble_install.sh
source /opt/ros/humble/setup.bash
export TURTLEBOT3_MODEL=burger
export ROS_DOMAIN_ID=30 #TURTLEBOT3
source /usr/share/gazebo/setup.sh #Required for some machines to launch gz properly
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
chmod 0700 /run/user/1000/
export RCUTILS_COLORIZED_OUTPUT=1

# This is for MY convenience for booting up ROS2 and such.
echo 🤖 ee4308 🤖
cd ~/ee4308
source install/setup.bash
